### ISSUE TITLE
Hostname verification when using HTTPS

### ISSUE THREAD

**Issue by basg** [lbetz/check_apache_status#2]
I noticed that check_apache_status failed in our setup when executing the check using HTTPS, returning `APACHE_STATUS UNKNOWN - HASH(0x19a5ca0).`
This seems to have to do with host name verification failing. 

After modifying line 79 from: `my $ua = LWP::UserAgent->new( protocols_allowed => ['http','https'], timeout => 15 );` to `my $ua = LWP::UserAgent->new( protocols_allowed => ['http','https'], timeout => 15, ssl_opts => {verify_hostname => 0 } );` (effectively switching off hostname verification), checks seem to execute with no problems. 

Perhaps a argument could be introduced that switches off hostname verification?

**Comment by lbetz** [comment]
Thx for your work. I’ll try to integrate it soon.

**Comment by lbetz** [comment]
pushed to master branch on https://github.com/lbetz/check_apache_status, option -N

**Comment by basg** [comment]
Many thanks for your prompt response!

**Comment by lbetz** [comment]
You’re welcome.
