### ISSUE TITLE
Exit plugin with CRITICAL if no response

### ISSUE THREAD

**Issue by prupert** [lbetz/check_apache_status#3]
Currently, the plugin will exit with `UNKNOWN` if the web server does not respond correctly to the request for the Apache status page. In our use case we would like to have the `CRITICAL` exit code, as this indicates that Apache is unresponsive. 

Would it be possible to make the exit code of the "<something failed getting apache status page>" condition configurable? E.g. 

Add the option
```
$options->arg(
  spec     => 'critical_on_failure|C',
  help     => 'exit with critical status when fetching status page failed',
  required => 0,
);
```
Add the condition at the end of the script
```
(...)
} else {

 if (defined($options->critical_on_failure)) {
    $status = 2;
  } else {
    $status = 3;
  }

  $plugin->plugin_exit( $status, $response->headers->title );

}
```

**Comment by lbetz** [comment]
For what kind of http code do you like to get a critical? Or only if the plugin timed out?

**Comment by prupert** [comment]
Thank you for that question, that could lead to a better implementation. 

A HTTP 5xx or time-out indicates a real problem with the Apache web server. In that case I would think a "critical" status is suitable.

For all other HTTP error codes (such as HTTP 4xx) or a correct HTTP status code (such as HTTP 200, but without actually responding with the mod_status page) it is most likely just a monitoring configuration issue, and thus "unknown" status is suitable.

**Comment by lbetz** [comment]
push to master, tagged version 1.3.0
