### ISSUE TITLE
Open slots threshold not working correctly

### ISSUE THREAD

**Issue by 0per8or** [lbetz/check_apache_status#4]
I want to define a warning and critical threshold for open slots, but it does not work as expected. In my understanding this value should go in warning or crtitical state if it **falls below** the defined thresholds.

I tried several different syntax like `:20,,`, `20:,,` or `20,,` but everytime the state changes to critical as it exceeds the defined critical threshold.

Busy and idle workers thresholds have not been tested.

**Comment by lbetz** [comment]
Should be
-w 20:,, -c 10:,,

to get a warning if less than 20 and a critical if less than 10 slots are opened.

**Comment by 0per8or** [comment]
Thanks for your help. The plugins works fine but it seems Icinga can not handle the colon in the performance data. It only shows 0.00 for warning and critical.
