### ISSUE TITLE
"Use of uninitialized value in sprintf" in Performance.pm

### ISSUE THREAD

**Issue by Subito** [lbetz/check_apache_status#5]
If I run the Plugin I get
`Use of uninitialized value in sprintf at /usr/local/lib/perl5/site_perl/Monitoring/Plugin/Performance.pm line 67.` (I'm using FreeBSD).
The corresponding line in the Performance.pm looks like this:
```
    my $out = sprintf "%s=%s%s;%s;%s;%s;%s",
        $label,
        $self->value,
        $self->_nvl($self->uom),
        $self->_nvl($self->warning),
        $self->_nvl($self->critical),
        $self->_nvl($self->min),
        $self->_nvl($self->max);
```
simply `curl`-ing the server works and I get the `/server-status` page as expected.

I have no idea how and why this happens. Seems like it gets triggered by the performance output. Do you have any ideas or input on how to debug this?

**Comment by ghost** [comment]
Same with CentOS 7

**Comment by ghost** [comment]
In my case this seems to be an issue with 2.4 MPM Event

```
Use of uninitialized value in sprintf at /usr/share/perl5/vendor_perl/Monitoring/Plugin/Performance.pm line 67.
Use of uninitialized value in sprintf at /usr/share/perl5/vendor_perl/Monitoring/Plugin/Performance.pm line 67.
Use of uninitialized value in sprintf at /usr/share/perl5/vendor_perl/Monitoring/Plugin/Performance.pm line 67.
Use of uninitialized value in sprintf at /usr/share/perl5/vendor_perl/Monitoring/Plugin/Performance.pm line 67.
APACHE_STATUS OK - OpenSlots:0 BusyWorkers: IdleWorkers: | OpenSlots=0;; BusyWorkers=;; IdleWorkers=;;```

I'll fork and fix this.

**Comment by ghost** [comment]
I've tried to reproduce this issue on macOS and discovered that this issue occures when trying to connect via SSL.

**Comment by ghost** [comment]
And this seems not to correlate with a redirect to SSL as GET requests are _redirectable_
```perl
DB<1> x $ua
0  LWP::UserAgent=HASH(0x7fd22158d238)
   'def_headers' => HTTP::Headers=HASH(0x7fd2215e1a10)
      'user-agent' => 'libwww-perl/6.27'
   'handlers' => HASH(0x7fd2215e1b00)
      'response_header' => HTTP::Config=ARRAY(0x7fd220defed0)
         0  HASH(0x7fd2209663f0)
            'callback' => CODE(0x7fd221590728)
               -> &LWP::UserAgent::__ANON__[/Users/yves/.plenv/versions/5.18.4/lib/perl5/site_perl/5.18.4/LWP/UserAgent.pm:741] in /Users/yves/.plenv/versions/5.18.4/lib/perl5/site_perl/5.18.4/LWP/UserAgent.pm:720-741
            'line' => '/Users/yves/.plenv/versions/5.18.4/lib/perl5/site_perl/5.18.4/LWP/UserAgent.pm:742'
            'm_media_type' => 'html'
            'owner' => 'LWP::UserAgent::parse_head'
   'local_address' => undef
   'max_redirect' => 7
   'max_size' => undef
   'no_proxy' => ARRAY(0x7fd22158fe70)
        empty array
   'protocols_allowed' => ARRAY(0x7fd2215902f0)
      0  'http'
      1  'https'
   'protocols_forbidden' => undef
   'proxy' => HASH(0x7fd2215dbc18)
        empty hash
   'requests_redirectable' => ARRAY(0x7fd22158cb00)
      0  'GET'
      1  'HEAD'
   'show_progress' => undef
   'ssl_opts' => HASH(0x7fd221590128)
      'verify_hostname' => 1
   'timeout' => 15
   'use_eval' => 1
``

**Comment by ghost** [comment]
Alright… I got it.

The path must be ```/server-status?auto``` and not ```/server-status/?auto``` as the second slash seems to bypass the server-status handler under some circumstances.

So if you have specified some exceptions for ProxyPass or setup RewriteRules to force redirects for all other requests the request to the server-status page gets redirected. And in this case the regexp does not match. I've added a UNKNOWN message for this.

@Subito You should check if the URL you may get redirected to is the status page.

**Comment by ghost** [comment]
Here's my PR

#6

**Comment by Subito** [comment]
Thanks for the fix, @yves-vogl! Can confirm that your PR fixes the issue :). Setting `--url` by hand is a workaround I can use in the meantime.
